# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Digital Team
tagline:             'Development docs, habits & practices'
description:         'Detailed documentation on our website development habits. From front-end development techniques, Git handling, processes, practices, code reviews, style guides and more, you will find it here'
url:                 https://www.york.ac.uk
baseurl:             'https://university-of-york.github.io/'
paginate:            5

# About/contact
author:
  name:              Rob Kendal
  url:               https://twitter.com/kendalmintcode
  email:             rob.kendal@york.ac.uk

# Custom vars
version:             1.0.0
