# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               University of York Development Docs
tagline:             'University of York Development Docs'
description:         'Detailed documentation on our website development habits. From front-end development techniques, Git handling, processes, practices, code reviews, style guides and more, you will find it here'
url:                 http://www.york.ac.uk/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Rob Kendal
  url:               https://twitter.com/kendalmintcode
  email:             rob.kendal@york.ac.uk

# Custom vars
version:             1.0.0
